# Generated by Django 5.0.7 on 2024-07-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('needs_fuel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=50)),
                ('assigned_driver', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('fuel_quantity', models.FloatField()),
                ('fuel_price_per_liter', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery_api.fueltype')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery_api.truck')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_to_deliver', models.FloatField()),
                ('delivered', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery_api.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinery_api.fuelstation')),
            ],
        ),
    ]
