# Generated by Django 5.0.6 on 2024-07-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='sells_api.station')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.CharField(max_length=100)),
                ('invoice_nit', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells_api.fuel')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells_api.pump')),
            ],
        ),
        migrations.CreateModel(
            name='PumpFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10, default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, default=0)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells_api.fuel')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells_api.pump')),
            ],
        ),
    ]
